--- #YAML:1.0
name:                Ham-APRS-DeviceID
version:             1.04
abstract:            APRS device identifier
license:             perl
author:              
    - Heikki Hannikainen <hessu@hes.iki.fi>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Ham::APRS::FAP:                1.16
    Test::More:                    0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
