--- #YAML:1.0
name:               Ham-APRS-DeviceID
version:            1.07
abstract:           APRS device identifier
author:
    - Heikki Hannikainen <hessu@hes.iki.fi>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Ham::APRS::FAP:  1.16
    Test::More:      0.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
